# Copyright(c) 2018 Asit Dhal.
# Distributed under the MIT License (http://opensource.org/licenses/MIT)

language: cpp
sudo: required
dist: trusty

#compiler:
#  - gcc
#  - clang

configuration:
  - Release
  - Debug

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test"]
        packages: ["g++-7", "ninja-build"]
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libfreetype6-dev alsa libasound2-dev
  - sudo add-apt-repository -y ppa:webkit-team/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev libstdc++6

script:
  - cd Builds/LinuxMakefile
  - make