version: 0.0.1-{build}

configuration:
  - Release
  - Debug

image: 
  - Visual Studio 2017

platform: 
  - x64

branches:
  only:
    - master

matrix:
  fast_finish: false
  exclude:
    - platform: win32
      image: Visual Studio 2017


build:
  parallel: true  

build_script:
    - git submodule update --init --recursive
    - ps: $env:BUILD_PATH=$env:APPVEYOR_BUILD_FOLDER + "\build_" + $env:platform
    - mkdir %BUILD_PATH%
    - cd %BUILD_PATH%
    - cmake %APPVEYOR_BUILD_FOLDER% -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%configuration%
    - cmake --build . --config %configuration% 

after_build:
  7z a %APPVEYOR_BUILD_FOLDER%\FrankfurterDesktop.7z %BUILD_PATH%\FrankfurterDesktop_artefacts\%configuration%\FrankfurterDesktop.exe

artifacts:
  - path: FrankfurterDesktop.7z
    name: FrankfurterDesktop