version: configuring.{build}
image: 
  - Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x64
clone_folder: c:\proj\CurrencyExchanger

init:
  - cmd: >-
    git clone git@github.com:WeAreROLI/JUCE.git
    cd c:\proj\CurrencyExchanger\Builds\VisualStudio2017\

install:
  - ps: |
    cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"

build:
  - cmd: >-
    MSBuild /nologo CurrencyExchanger.sln
after_build:
  - cmd: >-
    cd c:\SLBuild\throb\artifacts-%CONFIGURATION%
    if %PLATFORM% == x64 (echo Preparing to deploy win-64.zip) else (echo Preparing to deploy win-32.zip)
    if %PLATFORM% == x64 (ren win.zip win-64.zip) else (ren win.zip win-32.zip)
    cd ..
artifacts:
  - path: artifacts-Release/win-32.zip
    name: binary (32bit)
  - path: artifacts-Release/win-64.zip
    name: binary (64bit)
