version: configuring.{build}

image: 
  - Visual Studio 2017

install:
  - git clone --depth=1 --single-branch https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/JUCE"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%/JUCE"
  - cd extras\Projucer\Builds\VisualStudio2017\
  - msbuild.exe Projucer.sln /t:Build /p:Configuration=Release;Platform=x64
  - cd C:\projects\CurrencyExchange\Builds\VisualStudio2017
  - msbuild.exe CurrencyExchanger.sln /t:Build /p:Configuration=Release;Platform=x64
