version: configuring.{build}

image: 
  - Visual Studio 2017

environment:
  MSBUILD_FLAGS: /maxcpucount
  BOOST_ROOT: C:/Libraries/boost_1_59_0


install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set INCLUDE=C:\Libraries\boost_1_59_0;%INCLUDE%

build_script:
  - cd C:\projects\CurrencyExchange\Builds\VisualStudio2017
  - msbuild.exe CurrencyExchanger.sln /t:Build /p:Configuration=Release;Platform=x64

artifacts:
  - path: Builds\VisualStudio2017\x64\Release\App\CurrencyExchanger.exe
    name: CurrencyExchanger
